apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: appointment-system
  labels:
    app: appointment-system
data:
  POSTGRES_DB: "appointment_db"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres-service"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  ENVIRONMENT: "production"
